<a href="https://colab.research.google.com/github/dianegovindan/dianegovindan/blob/main/Q38.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 38**

In [34]:
import numpy as np
import pandas as pd
import statistics
import math
import scipy.stats
import statsmodels.api as sm

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.metrics import classification_report

import warnings
warnings.filterwarnings('ignore')

In [35]:
df_football = pd.read_csv('https://raw.githubusercontent.com/dianegovindan/dianegovindan/main/football_players.csv', encoding='latin-1')
df_football.head()

Name  Age Nationality  Overall  Acceleration  Aggression  \
0  Cristiano Ronaldo   32    Portugal     94.0          89.0        63.0   
1           L. Messi   30   Argentina     93.0          92.0        48.0   
2             Neymar   25      Brazil     92.0          94.0        56.0   
3          L. Suárez   30     Uruguay     92.0          88.0        78.0   
4           M. Neuer   31     Germany     92.0          58.0        29.0   

   Agility  Balance  Ball control  Composure  ...  Shot power  Sliding tackle  \
0     89.0     63.0          93.0       95.0  ...        94.0            23.0   
1     90.0     95.0          95.0       96.0  ...        85.0            26.0   
2     96.0     82.0          95.0       92.0  ...        80.0            33.0   
3     86.0     60.0          91.0       83.0  ...        87.0            38.0   
4     52.0     35.0          48.0       70.0  ...        25.0            11.0   

   Sprint speed  Stamina  Standing tackle  Strength  Vision  Volleys  \
0          91.0     92.0             31.0      80.0    85.0     88.0   
1          87.0     73.0             28.0      59.0    90.0     85.0   
2          90.0     78.0             24.0      53.0    80.0     83.0   
3          77.0     89.0             45.0      80.0    84.0     88.0   
4          61.0     44.0             10.0      83.0    70.0     11.0   

   Preferred Positions  Preferred Positions Type  
0               ST LW                    Forward  
1                  RW                    Forward  
2                  LW                    Forward  
3                  ST                    Forward  
4                  GK                 GoalKeeper  

[5 rows x 40 columns]

In [36]:
df_football['Overall'].value_counts().head(1)

66.0    1105
Name: Overall, dtype: int64

In [37]:
df_cb = df_football[df_football['Preferred Positions'].str.contains('CB')]
df_cb.head()

Name  Age Nationality  Overall  Acceleration  Aggression  Agility  \
10  Sergio Ramos   31       Spain     90.0          75.0        84.0     79.0   
17  G. Chiellini   32       Italy     89.0          68.0        92.0     59.0   
24    L. Bonucci   30       Italy     88.0          62.0        82.0     60.0   
25    J. Boateng   28     Germany     88.0          72.0        82.0     58.0   
26      D. Godín   31     Uruguay     88.0          62.0        86.0     63.0   

    Balance  Ball control  Composure  ...  Shot power  Sliding tackle  \
10     60.0          84.0       80.0  ...        79.0            91.0   
17     64.0          57.0       82.0  ...        78.0            90.0   
24     52.0          75.0       84.0  ...        74.0            88.0   
25     53.0          71.0       86.0  ...        79.0            90.0   
26     58.0          76.0       82.0  ...        67.0            89.0   

    Sprint speed  Stamina  Standing tackle  Strength  Vision  Volleys  \
10          77.0     84.0             89.0      81.0    63.0     66.0   
17          78.0     68.0             92.0      91.0    50.0     45.0   
24          72.0     73.0             88.0      85.0    74.0     58.0   
25          78.0     74.0             91.0      91.0    76.0     53.0   
26          67.0     67.0             86.0      80.0    52.0     47.0   

    Preferred Positions  Preferred Positions Type  
10                  CB                       Back  
17                  CB                       Back  
24                  CB                       Back  
25                  CB                       Back  
26                  CB                       Back  

[5 rows x 40 columns]

In [38]:
def class_find(score):

    class_cat = 0

    if score >=80:
        class_cat = 1
    elif score<70:
        class_cat = 3
    else:
        class_cat = 2

    return class_cat

In [58]:
# create class
df_cb['class'] = df_cb['Overall'].apply(class_find)
df_cb.tail(3000)

Name  Age          Nationality  Overall  Acceleration  \
2985         S. Kaya   26               Turkey     73.0          66.0   
2986    A. Rodríguez   33                 Peru     73.0          60.0   
2992        K. Rekik   22          Netherlands     73.0          66.0   
2997     S. Mitrovi?   27               Serbia     73.0          44.0   
2998     A. Mosquera   27             Colombia     73.0          72.0   
...              ...  ...                  ...      ...           ...   
17968  T. Brownsword   17              England     47.0          55.0   
17970     A. Kilgour   19              England     47.0          52.0   
17972      A. Conway   19  Republic of Ireland     47.0          60.0   
17974      J. Keeble   18              England     46.0          66.0   
17980      L. Sackey   18                Ghana     46.0          48.0   

       Aggression  Agility  Balance  Ball control  Composure  ...  \
2985         77.0     73.0     63.0          59.0       73.0  ...   
2986         75.0     61.0     67.0          51.0       74.0  ...   
2992         76.0     65.0     64.0          62.0       73.0  ...   
2997         77.0     47.0     46.0          58.0       70.0  ...   
2998         76.0     55.0     58.0          59.0       56.0  ...   
...           ...      ...      ...           ...        ...  ...   
17968        47.0     49.0     59.0          30.0       48.0  ...   
17970        56.0     60.0     51.0          42.0       38.0  ...   
17972        44.0     47.0     54.0          28.0       43.0  ...   
17974        40.0     45.0     48.0          34.0       37.0  ...   
17980        52.0     49.0     47.0          32.0       33.0  ...   

       Sliding tackle  Sprint speed  Stamina  Standing tackle  Strength  \
2985             71.0          70.0     65.0             75.0      70.0   
2986             62.0          63.0     45.0             76.0      76.0   
2992             75.0          68.0     70.0             73.0      80.0   
2997             73.0          45.0     67.0             78.0      85.0   
2998             71.0          70.0     74.0             75.0      76.0   
...               ...           ...      ...              ...       ...   
17968            54.0          63.0     59.0             51.0      50.0   
17970            43.0          55.0     61.0             46.0      68.0   
17972            43.0          58.0     52.0             48.0      48.0   
17974            49.0          60.0     52.0             52.0      42.0   
17980            43.0          49.0     55.0             44.0      67.0   

       Vision  Volleys  Preferred Positions  Preferred Positions Type  class  
2985     43.0     39.0                  CB                       Back      2  
2986     54.0     52.0                  CB                       Back      2  
2992     45.0     33.0                  CB                       Back      2  
2997     43.0     28.0                  CB                       Back      2  
2998     53.0     38.0               RB CB                       Back      2  
...       ...      ...                  ...                       ...    ...  
17968    32.0     21.0                  CB                       Back      3  
17970    31.0     19.0                  CB                       Back      3  
17972    40.0     33.0        CB LW LWB LB                       Back      3  
17974    28.0     24.0                  CB                       Back      3  
17980    22.0     19.0               ST CB                       Back      3  

[3000 rows x 41 columns]

In [40]:
#target is classes

y = df_cb['class']

In [41]:
y.head()

10    1
17    1
24    1
25    1
26    1
Name: class, dtype: int64

In [107]:
X = df_cb.drop(['Preferred Positions','Preferred Positions Type','class','Name','Nationality','Age'], axis = 1)
X.head()

Overall  Acceleration  Aggression  Agility  Balance  Ball control  \
10     90.0          75.0        84.0     79.0     60.0          84.0   
17     89.0          68.0        92.0     59.0     64.0          57.0   
24     88.0          62.0        82.0     60.0     52.0          75.0   
25     88.0          72.0        82.0     58.0     53.0          71.0   
26     88.0          62.0        86.0     63.0     58.0          76.0   

    Composure  Crossing  Curve  Dribbling  ...  Reactions  Short passing  \
10       80.0      66.0   73.0       61.0  ...       85.0           78.0   
17       82.0      58.0   60.0       58.0  ...       82.0           59.0   
24       84.0      44.0   56.0       69.0  ...       86.0           79.0   
25       86.0      69.0   56.0       67.0  ...       82.0           75.0   
26       82.0      55.0   49.0       53.0  ...       85.0           79.0   

    Shot power  Sliding tackle  Sprint speed  Stamina  Standing tackle  \
10        79.0            91.0          77.0     84.0             89.0   
17        78.0            90.0          78.0     68.0             92.0   
24        74.0            88.0          72.0     73.0             88.0   
25        79.0            90.0          78.0     74.0             91.0   
26        67.0            89.0          67.0     67.0             86.0   

    Strength  Vision  Volleys  
10      81.0    63.0     66.0  
17      91.0    50.0     45.0  
24      85.0    74.0     58.0  
25      91.0    76.0     53.0  
26      80.0    52.0     47.0  

[5 rows x 35 columns]

In [108]:
#split train-test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 911)

In [109]:
def k_model(k, x_trn, y_trn, x_tst, y_tst):

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(x_trn, y_trn)
    y_pred = knn.predict(x_tst)

    return f1_score(y_tst, y_pred, average = None) #print(classification_report(y_tst, y_pred))#, target_names=['World Class', 'Good', 'Mediocre']))

In [77]:
from sklearn.metrics import f1_score

In [110]:
k_model(1, X_train, y_train, X_test, y_test)

array([0.64705882, 0.78323699, 0.92298289])

In [111]:
k_model(2, X_train, y_train, X_test, y_test)

array([0.67605634, 0.80153649, 0.91450777])

In [112]:
k_model(3, X_train, y_train, X_test, y_test)

array([0.56140351, 0.78917379, 0.92486255])

In [113]:
k_model(4, X_train, y_train, X_test, y_test)

array([0.67741935, 0.82496608, 0.93174703])

In [114]:
k_model(5, X_train, y_train, X_test, y_test)

array([0.59259259, 0.81492109, 0.93495441])